---
title: "Code Retreat"
date: 12-08-2023
---

Info about the Code Retreats

Our next Code Retreats will take place 12 till 3 pm on Friday 8th December 2023 and 11:00 am till 2pm Tuesday 16th January 2024 at the University of York. Our instructors will be on hand to help you problem-solve the issues that arise as you work. Lunch will be provided and funding is available to support travel to the Code Retreat.

Cloud-SPAN Alumni contact cloud-span-project@york.ac.uk to register and invitations will be distributed shortly.

## What could you achieve?

* Working with your peers and with help from our instructors, you could:
* Revise our Metagenomics course 
* Get help organising and documenting your own analysis 
* Apply tools taught in Metagenomics to your own data
* Get help with Creating your own Amazon Web Services instance for Genomics
* Network with other genomics researchers 


## Pre-requisites 

* Attendees should have completed the a Cloud-SPAN course
* Attendees will need to bring their own laptop to this event
