---
title: "Core R"
date: 01-1-2020
---

Info about Core R

This online two-hour workshop is an introduction to R for complete beginners.  It teaches you how to find your way round RStudio, use the basic data types and structures in R and how to organise your work with scripts and projects. It also teaches you how to import data, summarise it and create and format a graph. The workshop assumes no prior experience of coding.


# Learning outcomes 

Join us for this free online two-hour workshop which provides an introduction to R for complete beginners. By the end of the course you will be able to;
- find your way around RStudio
- use the basic data types and structures in R
- organise your work with scripts and projects
- import data, summarise it and create and format a graph
- The workshop assumes no prior experience of coding.

# Registration
Registration for this course is now closed. 

There are 30 places available for this online course. Priority will be given to NERC funded students and researchers, as well as researchers from underrepresented groups, although we encourage everyone to apply. This course is free of charge. 

Application deadline: 12pm Monday 5th June. Applicants will be notified by Tuesday 6th June if they have been allocated a place. Scholarships and funding for headsets and monitors will be available. 
Scholarships and additional support

We recommend workshop participants have a second monitor and a headset. Dual monitors allow you to engage with the trainers, view materials shared on screen and other participants on one monitor while doing the activities on another. To support you with your learning we have funding to provide you with a headset and a monitor if you require this. To request this additional funding please indicate this in the registration form. Funds for the monitors and headsets will be distributed at the end of workshop to those participants who attend the session. 

We offer Diversity and Hardship Scholarships to enable members of underrepresented groups and those with financial difficulties to participate in our training courses.  To apply for a scholarship please complete the relevant questions in the registration form before the deadline. Submissions after this date will not be considered. All applicants will be notified of the results 2-3 days after the submission deadline.


