project:
  type: website
  output-dir: docs

website:
  title: "Evelyn Greeves"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd

format:
  html:
    theme: minty
    css: styles.css
    page-layout: full

editor: visual

