project:
  type: website
  output-dir: docs

website:
#  title: 
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    left: 
      - "Copyright 2023"

format:
  html:
#    theme:
    page-layout: full

editor: visual

