project:
  type: website
  output-dir: docs

date-format: YYYY-MM-DD  

website:
  title: Cloud-SPAN
  favicon: images/cloudspan_favicon_32x32.png
  site-url: https://cloud-span.github.io/cloud-span-quarto-site/
  cookie-consent:
    type: implied
    style: headline
    palette: light
  google-analytics: "G-77HC85CPEX"
  navbar:
    title: false
    logo: images/logo_cloud_only.png
    right:
      - text: Home
        href: index.qmd
      - text: About
        menu: 
          - text: About the project
            href: about.qmd
          - text: Our aims
            href: cloud-span-aims.qmd
          - text: Impact
            href: impact.qmd
          - text: DaSH Partners
            href: DaSH.qmd

      - self_study_courses.qmd
      - upcoming_courses.qmd
      - blogs.qmd
      - contact-us.qmd
          
  page-footer:
    left: 
      All content licensed under {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}
      [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    center:
      - href: https://github.com/Cloud-SPAN
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/SpanCloud
        icon: twitter
        aria-label: Twitter
      - href: mailto:cloud-span-project@york.ac.uk
        icon: envelope
    right: 
      Built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)

format:
  html:
    theme:
    - styles.scss
    mainfont: Montserrat
    page-layout: full

editor: visual

