project:
  type: website
  output-dir: docs

website:
  title: Cloud-SPAN
  favicon: images/cloudspan_favicon_32x32.png
  site-url: https://cloud-span.github.io/cloud-span-quarto-site/
  navbar:
    right:
      - text: Home
        href: index.qmd
      - about.qmd
      - self_study_courses.qmd
      - upcoming_courses.qmd
      - blogs.qmd
  page-footer: 
    left: 
      - "Copyright 2023"

format:
  html:
    theme:
    - styles.scss
    page-layout: full

editor: visual

