
---
title: "DaSH Partners"
title-block-banner: false
max-width: 1400px
---

# Innovation Scholars: Data Science Training in Health and Bioscience

Cloud-SPAN is one of nine projects funded via the (UKRI Innovation Scholars Initiative)[https://www.ukri.org/opportunity/innovation-scholars-data-science-training-in-health-bioscience/]. 

The project teams have fulfilled UKRI’s brief to deliver innovative training programmes to upskill health and bioscience researchers in data management and analysis at an impressive level. The training resources created have provided learners with a plethora of opportunities to learn new skills in a wide range of subject areas. Crucially, the learning resources are relevant and impactful to learners with any degree of experience; beginners to experienced data scientists are catered for.  

The training opportunities were very accessible with a range of delivery modes and styles. Nearly 5900 person-training episodes have occurred over 108 events. All projects have enhanced community engagement using innovative technology or approaches and several had dedicated Community leads. Some successful examples include development around a metaverse training centre (L2D), code retreats, hackathons and mentoring (IDEAS, ELIXIR-UK DaSH, Cloud-SPAN), live coding (IDEAS, Ed-DaSH, Cloud-SPAN, L2D) and deployment on the FutureLearn platform (DataCAMPP & KCL Enabling the big data revolution through skills training).*

# Learn more about the projects 

(Data CAMPP)[https://www.nottingham.ac.uk/research/groups/cvl/projects/data-cammp/data-cammp.aspx] 
Innovative training in data capture, analysis and management for plant phenotyping. 

(Ed-DaSH)[https://edcarp.github.io/Ed-DaSH/] 
Data driven life science skills development – equipping society for the future - Ed-DaSH is a Data Science training programme for Health and Biosciences 

(ELIXIR-UK: FAIR data stewardship training)[https://elixiruknode.org/activities/elixir-dash-fellowship/] 
Professionalising data stewardship in the life sciences

Health and bioscience IDEAS – imaging, data structures, genetics and analytical strategies 
https://healthbioscienceideas.github.io/ 

Innovation Scholars Programme - Big Data Skills Training 
https://innovationscholars.er.kcl.ac.uk/training/ 

Learn to Discover (L2D): A training platform in data sciences and machine learning for biomedicine and health researchers
https://learntodiscover.ai/ 

Radiance: Rigorous training in longitudinal data science 
https://radiance.org.uk/ 

T3connect: Train the trainer in data science for pathogen genomics and surveillance. Expanding pathogen genomics expertise across the UK 
https://t3connect.org/


* Data collated from Cloud-SPAN, Data CAMPP, Ed-DaSH, IDEAS, ELIXIR-UK FAIR Data Fellowship, Innovation Scholars Programme - Big Data Skills Training, L2D, Radiance, T3connect, projects in April 2023 
