---
page-layout: custom
listing:
  id: homepage-content
  #type: grid
  template: gallery.ejs
  contents: homepage-content.yaml
  grid-item-border: false
---

::: hero
::: hero-content
::: hero-title
Welcome to Cloud-SPAN
:::
:::
:::

::: content-container
::: pullout-text
::: pullout-container
::: {.pullout-block .blue-background}
Cloud-SPAN trains researchers, and the research software engineers that support them, to run specialised analyses on cloud-based high-performance computing (HPC) infrastructure. Cloud-SPAN is developing highly accessible resources which integrate with existing Carpentries courses.

We offer Diversity Scholarships to cover travel and/or childcare to enable members of underrepresented groups to participate in online or in-person training.

:::
:::
:::
:::


::: content-container
::: {#homepage-content}
:::
:::

::: content-container
Cloud-SPAN was established in March 2021 initially as a 2-year collaboration between the University of York and The Software Sustainability Institute funded by the UKRI innovation scholars award, project reference: MR/V038680/1. Additional funding from the Natural Environment Research Council, project references: NE/X006999/1 and NE/Y003527/1 allows the project to be extended until January 2024.
:::
