---
title: "Cloud-SPAN awarded NERC funding to expand training courses"
date: 2022/09/05
author: Sarah Dowsland
categories:
 - Announcements
 - Open science
---

The [Cloud-SPAN](https://cloud-span.york.ac.uk/) team has been awarded a grant to expand our training to the Natural Environment Research Council (NERC) remit under the [Advanced training for early-career environmental scientists](https://www.ukri.org/opportunity/run-advanced-training-for-early-career-environmental-scientists) call. We will be developing an accessible online course "Getting started with High Performance Computing: FAIR training for environmental scientists" using the same cloud-based infrastructure used in our [other courses](https://cloud-span.york.ac.uk/train-with-us). We will supply AWS services to up to 60 participants undertaking the course either in tutor-led workshops or by self-study.

Those needing funds for childcare or accessibility to enable their participation in the training will be able apply for a Scholarship and up to 30 participants will receive headsets and second monitors facilitate online engagement. The course will be running in April 2023 - please let your ecology colleagues know to look out for the course!

###  **Key info**

🔷 [Metagenomics with High Performance Computing](https://cloud-span.york.ac.uk/train-with-us/specialised-skills#h.jqgzsdc8hbla) ▶ 11-21 April (Online workshop)

🔷 Scholarship deadline 13 March

🔷 [Register for the online workshop](https://forms.gle/BFWKWtTeMLBjZr559)

🔷 [Register for the self-study mode](https://forms.gle/sV534UfAwiep2iGq9)